__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
protected_areas_in_europe:
    runtime: 239
    memory: 64000
settlements:
    cores: 4
    runtime: 240
shared_coast:
    cores: 4
    runtime: 60
slope_in_europe:
    cores: 4
elevation_in_europe:
    cores: 4
eez_eligibility:
    cores: 4
shared_coast:
    cores: 4
sensitivities:
    cores: 4
capacityfactor_timeseries:
    memory: 128000
    runtime: 180
time_average_capacityfactor_map:
    memory: 32000
national_boundaries:
    runtime: 60
administrative_borders_lau:
    runtime: 60
buffer_buildings_high_resolution:
    memory: 80000
    runtime: 120
buffer_buildings_in_europe:
    memory: 128000
    runtime: 120
    cores: 4
filter_2p5m_esm:
    memory: 48000
    runtime: 60
