snakemake:
    max-threads: 4
crs: "EPSG:4326"
scope:
    countries:
        - "Germany"
    bounds:
        x_min: 5 # in degrees east
        x_max: 15.1  # in degrees east
        y_min: 47  # in degrees north
        y_max: 55.2  # in degrees north
layers:
    continental:
        Germany: nuts0
    national:
        Germany: nuts0
    regional:
        # The link between NUTS and administrative units unfortunately is not obvious.
        # It's not documented anywhere -- at least I could not find any information.
        # Hence, I am using GADM here instead.
        # Validation source: https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country
        Germany: gadm1 # match 16
    municipal:
        Germany: lau2
parameters:
    maximum-installable-power-density: # this is not the yield, but the density of installed power
        pv-on-tilted-roofs: 160 # [W/m^2] from (Gagnon:2016, Klauser:2016), i.e. 16% efficiency
        pv-on-flat-areas: 80 # [W/m^2] from (Gagnon:2016, Klauser:2016, Wirth:2017)
        onshore-wind: 8 # [W/m^2] from (European Environment Agency, 2009)
        offshore-wind: 15 # [W/m^2] from (European Environment Agency, 2009)
    availability:
        wind-onshore: 0.97 # [-] from (European Environment Agency, 2009)
        wind-offshore: 0.9 # [-] from (European Environment Agency, 2009)
    ninja: # change these with caution as the renewables.ninja simulations are not in the loop, see README
        resolution-grid: 50 # [km^2] corresponding to MERRA resolution
        pv-performance-ratio: 0.9
        hub-height:
            onshore: 105 # m, median hub height of V90/2000 in Europe between 2010 and 2018
            offshore: 87 # m, median hub height of SWT-3.6-107 in Europe between 2010 and 2018
        turbine:
            onshore: "vestas v90 2000" # most built between 2010 and 2018 in Europe
            offshore: "siemens swt 3.6 107" # most built between 2010 and 2018 in Europe
    max-slope:
        pv: 10 # [°] (AlGarni:2018)
        wind: 20 # [°] (McKenna:2014)
    max-depth-offshore: -50
    max-building-share: 0.01 # Above, a pixel cannot be used for energy farms. Equals roughly 900m2
    max-urban-green-share: 0.01 # Above, a pixel cannot be used for energy farms. Equals roughly 900m2. Removes e.g. Berlin's Tempelhofer Feld.
scenarios:
    technical-potential:
        use-protected-areas: True
        pv-on-farmland: True
        share-farmland-used: 1.0
        share-forest-used-for-wind: 1.0
        share-other-land-used: 1.0
        share-offshore-used: 1.0
        share-rooftops-used: 1.0
    technical-potential-env-protection:
        use-protected-areas: False
        pv-on-farmland: True
        share-farmland-used: 1.0
        share-forest-used-for-wind: 1.0
        share-other-land-used: 1.0
        share-offshore-used: 1.0
        share-rooftops-used: 1.0
